
package proyectois2;

import java.sql.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Daniela Espinosa
 */
public class Frm_MuestraProducto extends javax.swing.JFrame {

    DefaultTableModel model;
    
    public Frm_MuestraProducto() {
        initComponents();
        AjustarVentana();
        try{
            actualizarTabla();
        }catch(Exception e){
            
        }
    }
    
    private void AjustarVentana(){
        //Centrar Ventana
        this.setLocationRelativeTo(null);  
        
        //Bloquear Tamanio
        this.setResizable(false);
    }
    
    public final void actualizarTabla() throws Exception{
    DefaultTableModel modelo = new DefaultTableModel();
        AccesoBD bd = new AccesoBD();
        ResultSet rs = bd.getTabla("SELECT codigo, stock, descripcion, precio FROM articulo");
        modelo.setColumnIdentifiers(new Object[]{"Código", "Cantidad", "Descripción", "Precio"});
        try{
            while(rs.next()){
                modelo.addRow(new Object[]{rs.getString("codigo"), rs.getInt("stock"),
                rs.getString("descripcion"), rs.getDouble("precio")});
            }
            jtMuestraProductos.setModel(modelo);
        }
        catch(SQLException e){
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpMuestraProducto = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtMuestraProductos = new javax.swing.JTable();
        lblTitulo2 = new javax.swing.JLabel();
        lblTitulo1 = new javax.swing.JLabel();
        txtBuscaProducto = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Inventario de Productos");

        jpMuestraProducto.setBackground(new java.awt.Color(255, 102, 102));
        jpMuestraProducto.setToolTipText("");

        jtMuestraProductos = new javax.swing.JTable(){
            public boolean isCellEditable (int rowIndex, int colIndex){
                return false;
            }
        };
        jtMuestraProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtMuestraProductos.setGridColor(new java.awt.Color(102, 0, 102));
        jtMuestraProductos.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jtMuestraProductos);

        lblTitulo2.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        lblTitulo2.setForeground(new java.awt.Color(102, 0, 102));
        lblTitulo2.setText("Búsqueda:");
        lblTitulo2.setPreferredSize(new java.awt.Dimension(34, 40));

        lblTitulo1.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 36)); // NOI18N
        lblTitulo1.setForeground(new java.awt.Color(102, 0, 102));
        lblTitulo1.setText("Inventario de Productos");

        txtBuscaProducto.setPreferredSize(new java.awt.Dimension(6, 45));
        txtBuscaProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscaProductoKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jpMuestraProductoLayout = new javax.swing.GroupLayout(jpMuestraProducto);
        jpMuestraProducto.setLayout(jpMuestraProductoLayout);
        jpMuestraProductoLayout.setHorizontalGroup(
            jpMuestraProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpMuestraProductoLayout.createSequentialGroup()
                .addContainerGap(74, Short.MAX_VALUE)
                .addComponent(lblTitulo1)
                .addGap(71, 71, 71))
            .addGroup(jpMuestraProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jpMuestraProductoLayout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(lblTitulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBuscaProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpMuestraProductoLayout.setVerticalGroup(
            jpMuestraProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMuestraProductoLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(lblTitulo1)
                .addGap(45, 45, 45)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(jpMuestraProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBuscaProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpMuestraProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpMuestraProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscaProductoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscaProductoKeyPressed
        // TODO add your handling code here:
        AccesoBD bd = new AccesoBD();
        String[] Titulos = {"Código", "stock", "Descripcion", "Precio"};
        String[] Registro = new String[50];
        
        String sql = "SELECT * FROM articulo WHERE codigo LIKE '%" + txtBuscaProducto.getText()+ "%'"
            + "OR stock LIKE '%" + txtBuscaProducto.getText() + "%'"
            + "OR descripcion LIKE '%" + txtBuscaProducto.getText() + "%'"
            + "OR precio LIKE '%" + txtBuscaProducto.getText() + "%'";
        
        model = new DefaultTableModel(null,Titulos);
        try {
            bd.conectaBD();
            Statement sta = bd.getConexion().createStatement();
            ResultSet rs= sta.executeQuery(sql);
            
            while(rs.next()){
                Registro[0] = rs.getString("codigo");
                Registro[1] = rs.getString("stock");
                Registro[2] = rs.getString("descripcion");
                Registro[3] = rs.getString("precio");
                model.addRow(Registro);
            }
            jtMuestraProductos.setModel(model);
        } catch (Exception ex) {
            
        }
    }//GEN-LAST:event_txtBuscaProductoKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_MuestraProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_MuestraProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_MuestraProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_MuestraProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_MuestraProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpMuestraProducto;
    private javax.swing.JTable jtMuestraProductos;
    private javax.swing.JLabel lblTitulo1;
    private javax.swing.JLabel lblTitulo2;
    private javax.swing.JTextField txtBuscaProducto;
    // End of variables declaration//GEN-END:variables
}
