/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectois2;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PJ_Yeah
 */
public class Frm_ModificaFabricante extends javax.swing.JFrame {

    /**
     * Creates new form Frm_ModificaFabricante
     */
    
    Frm_ActualizaDatosFabricante actualizaDatosFabricante;
    DefaultTableModel model;
    
    public Frm_ModificaFabricante() {
        initComponents();
        AjustarVentana();
        try {
            actualizarTabla();
        } catch (Exception ex) {
            Logger.getLogger(Frm_ModificaFabricante.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void AjustarVentana(){
        //Centrar Ventana
        this.setLocationRelativeTo(null);  
        
        //Bloquear Tamanio
        this.setResizable(false);
    }
    
    private void actualizarTabla() throws Exception{
    DefaultTableModel modelo = new DefaultTableModel();
        AccesoBD bd = new AccesoBD();
        ResultSet rs = bd.getTabla("SELECT id_fabricante, nombre_fabricante FROM fabricante");
        modelo.setColumnIdentifiers(new Object[]{"Código", "Nombre Frabricante"});
        try{
            while(rs.next()){
                modelo.addRow(new Object[]{rs.getInt("id_fabricante"), rs.getString("nombre_fabricante")});
            }
            jtMuestraFabricanteParaModificar.setModel(modelo);
        }
        catch(SQLException e){
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpModificaProducto = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtMuestraFabricanteParaModificar = new javax.swing.JTable();
        btnBuscaModificaFabricante = new javax.swing.JButton();
        txtCodigoaBuscarModifica = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modificar Fabricante");

        jpModificaProducto.setBackground(new java.awt.Color(242, 230, 53));

        jtMuestraFabricanteParaModificar = new javax.swing.JTable(){
            public boolean isCellEditable (int rowIndex, int colIndex){
                return false;
            }
        };
        jtMuestraFabricanteParaModificar.setBackground(new java.awt.Color(242, 230, 53));
        jtMuestraFabricanteParaModificar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Código", "Nombre"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtMuestraFabricanteParaModificar.setGridColor(new java.awt.Color(110, 13, 37));
        jtMuestraFabricanteParaModificar.getTableHeader().setReorderingAllowed(false);
        jtMuestraFabricanteParaModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtMuestraFabricanteParaModificarMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtMuestraFabricanteParaModificar);

        btnBuscaModificaFabricante.setBackground(new java.awt.Color(241, 235, 228));
        btnBuscaModificaFabricante.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btnBuscaModificaFabricante.setForeground(new java.awt.Color(167, 152, 139));
        btnBuscaModificaFabricante.setText("Modificar");
        btnBuscaModificaFabricante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaModificaFabricanteActionPerformed(evt);
            }
        });

        txtCodigoaBuscarModifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoaBuscarModificaActionPerformed(evt);
            }
        });
        txtCodigoaBuscarModifica.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodigoaBuscarModificaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoaBuscarModificaKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(110, 13, 37));
        jLabel1.setText("Búsqueda de Fabricante");

        javax.swing.GroupLayout jpModificaProductoLayout = new javax.swing.GroupLayout(jpModificaProducto);
        jpModificaProducto.setLayout(jpModificaProductoLayout);
        jpModificaProductoLayout.setHorizontalGroup(
            jpModificaProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpModificaProductoLayout.createSequentialGroup()
                .addGroup(jpModificaProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpModificaProductoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(jpModificaProductoLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jpModificaProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpModificaProductoLayout.createSequentialGroup()
                                .addComponent(txtCodigoaBuscarModifica, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55)
                                .addComponent(btnBuscaModificaFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpModificaProductoLayout.setVerticalGroup(
            jpModificaProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpModificaProductoLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(jpModificaProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBuscaModificaFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodigoaBuscarModifica, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpModificaProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpModificaProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtMuestraFabricanteParaModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtMuestraFabricanteParaModificarMouseClicked
        // TODO add your handling code here:
        int col = jtMuestraFabricanteParaModificar.getSelectedRow();

        txtCodigoaBuscarModifica.setText(jtMuestraFabricanteParaModificar.getModel().
            getValueAt(col, 0).toString());
    }//GEN-LAST:event_jtMuestraFabricanteParaModificarMouseClicked

    private void btnBuscaModificaFabricanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaModificaFabricanteActionPerformed
        // TODO add your handling code here:
        Fabricante f = new Fabricante(); String _codigo;
        boolean pass = false;
        _codigo = txtCodigoaBuscarModifica.getText();
        ProyectoIS2._Fab = _codigo;

        do{
            try {
                if(f.verificaCodigo(_codigo)){
                    pass = true;
                    setVisible(false);
                    actualizaDatosFabricante = new Frm_ActualizaDatosFabricante();
                    actualizaDatosFabricante.setVisible(true);
                }
                else if(txtCodigoaBuscarModifica.getText().equals("")){
                    JOptionPane.showMessageDialog(null, "El CÓDIGO ingresado no se encuentra"
                        + " registrado, ingrese uno valido o escoja uno de los que se muestran en la tabla...", "ATENCIÓN",
                        JOptionPane.INFORMATION_MESSAGE);
                    txtCodigoaBuscarModifica.setText("");
                    return;
                }
                else{
                    JOptionPane.showMessageDialog(null, "El CÓDIGO ingresado no se encuentra"
                        + " registrado, ingrese uno valido o escoja uno de los que se muestran en la tabla...", "ATENCIÓN",
                        JOptionPane.INFORMATION_MESSAGE);
                    txtCodigoaBuscarModifica.setText("");
                    return;
                }
            } catch (Exception e) {

            }
        }while(!pass);
    }//GEN-LAST:event_btnBuscaModificaFabricanteActionPerformed

    private void txtCodigoaBuscarModificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoaBuscarModificaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoaBuscarModificaActionPerformed

    private void txtCodigoaBuscarModificaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoaBuscarModificaKeyPressed
        // TODO add your handling code here
        AccesoBD bd = new AccesoBD();
        String[] Titulos = {"Código", "Nombre Fabricante"};
        String[] Registro = new String[50];

        String sql = "SELECT * FROM fabricante WHERE id_fabricante LIKE '%" + txtCodigoaBuscarModifica.getText()+ "%'"
        + "OR nombre_fabricante LIKE '%" + txtCodigoaBuscarModifica.getText() + "%'";

        model = new DefaultTableModel(null,Titulos);
        try {
            bd.conectaBD();
            Statement sta = bd.getConexion().createStatement();
            ResultSet rs= sta.executeQuery(sql);

            while(rs.next()){
                Registro[0] = rs.getString("id_fabricante");
                Registro[1] = rs.getString("nombre_fabricante");
                model.addRow(Registro);
            }
            jtMuestraFabricanteParaModificar.setModel(model);
        } catch (Exception ex) {

        }
    }//GEN-LAST:event_txtCodigoaBuscarModificaKeyPressed

    private void txtCodigoaBuscarModificaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoaBuscarModificaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoaBuscarModificaKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_ModificaFabricante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_ModificaFabricante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_ModificaFabricante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_ModificaFabricante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_ModificaFabricante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscaModificaFabricante;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel jpModificaProducto;
    private javax.swing.JTable jtMuestraFabricanteParaModificar;
    private javax.swing.JTextField txtCodigoaBuscarModifica;
    // End of variables declaration//GEN-END:variables
}
