
package proyectois2;

import java.awt.event.KeyEvent;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Daniela Espinosa
 */
public class Frm_EntradaStock extends javax.swing.JFrame {
    DefaultTableModel model;

    public Frm_EntradaStock() {
        initComponents();
        AjustarVentana();
        try {
            actualizarTabla();
        } catch (Exception ex) {
            
        }
    }
    
    private void AjustarVentana(){
        //Centrar Ventana
        this.setLocationRelativeTo(null);  
        
        //Bloquear Tamanio
        this.setResizable(false);
    }
    
    public final void actualizarTabla() throws Exception{
    DefaultTableModel modelo = new DefaultTableModel();
        AccesoBD bd = new AccesoBD();
        ResultSet rs = bd.getTabla("SELECT codigo, stock, descripcion, precio FROM articulo");
        modelo.setColumnIdentifiers(new Object[]{"Código", "Stock", "Descripción", "Precio"});
        try{
            while(rs.next()){
                modelo.addRow(new Object[]{rs.getString("codigo"), rs.getInt("stock"),
                rs.getString("descripcion"), rs.getDouble("precio")});
            }
            jtModificaStock.setModel(modelo);
        }
        catch(SQLException e){
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtModificaStock = new javax.swing.JTable();
        txtModificaInventario = new javax.swing.JTextField();
        btnBuscaModificaInventario = new javax.swing.JButton();
        lblTitulo1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modificar Stock");

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));

        jtModificaStock = new javax.swing.JTable(){
            public boolean isCellEditable (int rowIndex, int colIndex){
                return false;
            }
        };
        jtModificaStock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Cantidad", "Descripción", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtModificaStock.getTableHeader().setReorderingAllowed(false);
        jtModificaStock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtModificaStockMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtModificaStock);

        txtModificaInventario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtModificaInventarioKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtModificaInventarioKeyTyped(evt);
            }
        });

        btnBuscaModificaInventario.setBackground(new java.awt.Color(251, 227, 185));
        btnBuscaModificaInventario.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btnBuscaModificaInventario.setText("Modificar");
        btnBuscaModificaInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaModificaInventarioActionPerformed(evt);
            }
        });

        lblTitulo1.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 36)); // NOI18N
        lblTitulo1.setForeground(new java.awt.Color(102, 0, 102));
        lblTitulo1.setText("Modificación de Stock");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(197, 197, 197)
                                .addComponent(txtModificaInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(80, 80, 80)
                                .addComponent(btnBuscaModificaInventario))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(124, 124, 124)
                                .addComponent(lblTitulo1)))
                        .addGap(0, 144, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(lblTitulo1)
                .addGap(45, 45, 45)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscaModificaInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtModificaInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtModificaInventarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtModificaInventarioKeyTyped

    }//GEN-LAST:event_txtModificaInventarioKeyTyped

    private void btnBuscaModificaInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaModificaInventarioActionPerformed
        // TODO add your handling code here:
        Articulo a = new Articulo(); String _codigo; int _cantidad = 0, _stockAnterior = 0;
        boolean pass = false;
        _codigo = txtModificaInventario.getText();
        try{
            if(a.verificaCodigo(_codigo)){                
                do{
                    try{
                        _cantidad = Integer.parseInt(JOptionPane.showInputDialog(null,"Ingrese "
                            + "la cantidad que desea agregale al producto","",JOptionPane.INFORMATION_MESSAGE));
                        pass = true;
                    }catch(Exception ex){
                        JOptionPane.showMessageDialog(null, "Ingrese una CANTIDAD que sea valida",
                                "", JOptionPane.ERROR_MESSAGE);
                        pass = false;
                    }
                }while(_cantidad<0||!pass);
                _stockAnterior = a.obtenerStock(_codigo);                
                a.setCantidad(_cantidad+_stockAnterior);
                a.modificaStock(_codigo);
                txtModificaInventario.setText("");
                JOptionPane.showMessageDialog(null, "El stock del producto se ha"
                    + " modificado con éxito...!!!","",JOptionPane.INFORMATION_MESSAGE); 
                actualizarTabla();
                setVisible(false);
            }
            else{
                JOptionPane.showMessageDialog(null, "El CÓDIGO ingresado no se encuentra"
                    + " registrado, ingrese uno de los que se muestran en la tabla...", "",
                    JOptionPane.INFORMATION_MESSAGE);
                txtModificaInventario.setText("");
            }
        }catch(Exception e){
            
        }
        
    }//GEN-LAST:event_btnBuscaModificaInventarioActionPerformed

    private void txtModificaInventarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtModificaInventarioKeyPressed
        // TODO add your handling code here:
        AccesoBD bd = new AccesoBD();
        String[] Titulos = {"Código", "Stock", "Descripcion", "Precio"};
        String[] Registro = new String[50];
        
        String sql = "SELECT * FROM articulo WHERE codigo LIKE '%" + txtModificaInventario.getText()+ "%'"
            + "OR Stock LIKE '%" + txtModificaInventario.getText() + "%'"
            + "OR descripcion LIKE '%" + txtModificaInventario.getText() + "%'"
            + "OR precio LIKE '%" + txtModificaInventario.getText() + "%'";
        
        model = new DefaultTableModel(null,Titulos);
        try {
            bd.conectaBD();
            Statement sta = bd.getConexion().createStatement();
            ResultSet rs= sta.executeQuery(sql);
            
            while(rs.next()){
                Registro[0] = rs.getString("codigo");
                Registro[1] = rs.getString("stock");
                Registro[2] = rs.getString("descripcion");
                Registro[3] = rs.getString("precio");
                model.addRow(Registro);
            }
            jtModificaStock.setModel(model);
        } catch (Exception ex) {
            
        }
    }//GEN-LAST:event_txtModificaInventarioKeyPressed

    private void jtModificaStockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtModificaStockMouseClicked
        // TODO add your handling code here:
        int col = jtModificaStock.getSelectedRow();
        
        txtModificaInventario.setText(jtModificaStock.getModel().
                getValueAt(col, 0).toString());
    }//GEN-LAST:event_jtModificaStockMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_EntradaStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_EntradaStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_EntradaStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_EntradaStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_EntradaStock().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscaModificaInventario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtModificaStock;
    private javax.swing.JLabel lblTitulo1;
    private javax.swing.JTextField txtModificaInventario;
    // End of variables declaration//GEN-END:variables
}
