/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectois2;

/**
 *
 * @author Daniela Espinosa
 */
public class Frm_TodoFabricante extends javax.swing.JFrame {

    Frm_RegistraFabricante registraFabricante;
    Frm_MuestraFabricante  muestraFabricante;
    Frm_ModificaFabricante modificaFabricante;
    
    public Frm_TodoFabricante() {
        initComponents();
        AjustarVentana();
    }
    
    private void AjustarVentana(){
        //Centrar Ventana
        this.setLocationRelativeTo(null);  
        
        //Bloquear Tamanio
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpMenuFabricante = new javax.swing.JPanel();
        lblTitulo1 = new javax.swing.JLabel();
        btnRegistrarFabricante = new javax.swing.JButton();
        btnMostrarFabricante = new javax.swing.JButton();
        btnModificaFabricante = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Menú Fabricante");

        jpMenuFabricante.setBackground(new java.awt.Color(242, 230, 53));

        lblTitulo1.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 36)); // NOI18N
        lblTitulo1.setForeground(new java.awt.Color(110, 13, 37));
        lblTitulo1.setText("Menú Fabricante");

        btnRegistrarFabricante.setBackground(new java.awt.Color(241, 235, 228));
        btnRegistrarFabricante.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btnRegistrarFabricante.setForeground(new java.awt.Color(167, 152, 139));
        btnRegistrarFabricante.setText("Registrar Fabricante");
        btnRegistrarFabricante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarFabricanteActionPerformed(evt);
            }
        });

        btnMostrarFabricante.setBackground(new java.awt.Color(241, 235, 228));
        btnMostrarFabricante.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btnMostrarFabricante.setForeground(new java.awt.Color(167, 152, 139));
        btnMostrarFabricante.setText("Mostrar Fabricante");
        btnMostrarFabricante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarFabricanteActionPerformed(evt);
            }
        });

        btnModificaFabricante.setBackground(new java.awt.Color(241, 235, 228));
        btnModificaFabricante.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btnModificaFabricante.setForeground(new java.awt.Color(167, 152, 139));
        btnModificaFabricante.setText("Modificar Fabricante");
        btnModificaFabricante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificaFabricanteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpMenuFabricanteLayout = new javax.swing.GroupLayout(jpMenuFabricante);
        jpMenuFabricante.setLayout(jpMenuFabricanteLayout);
        jpMenuFabricanteLayout.setHorizontalGroup(
            jpMenuFabricanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMenuFabricanteLayout.createSequentialGroup()
                .addGroup(jpMenuFabricanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpMenuFabricanteLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(lblTitulo1))
                    .addGroup(jpMenuFabricanteLayout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addGroup(jpMenuFabricanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnModificaFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jpMenuFabricanteLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jpMenuFabricanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnRegistrarFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnMostrarFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(87, 87, 87))
        );
        jpMenuFabricanteLayout.setVerticalGroup(
            jpMenuFabricanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMenuFabricanteLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(lblTitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(btnRegistrarFabricante)
                .addGap(45, 45, 45)
                .addComponent(btnMostrarFabricante)
                .addGap(45, 45, 45)
                .addComponent(btnModificaFabricante)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 544, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpMenuFabricante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 359, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpMenuFabricante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarFabricanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarFabricanteActionPerformed
        // TODO add your handling code here:
        registraFabricante = new Frm_RegistraFabricante();
        registraFabricante.setVisible(true);
    }//GEN-LAST:event_btnRegistrarFabricanteActionPerformed

    private void btnMostrarFabricanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarFabricanteActionPerformed
        // TODO add your handling code here:
        muestraFabricante = new Frm_MuestraFabricante();
        muestraFabricante.setVisible(true);
    }//GEN-LAST:event_btnMostrarFabricanteActionPerformed

    private void btnModificaFabricanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificaFabricanteActionPerformed
        // TODO add your handling code here:
        modificaFabricante = new Frm_ModificaFabricante();
        modificaFabricante.setVisible(true);
    }//GEN-LAST:event_btnModificaFabricanteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_TodoFabricante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_TodoFabricante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_TodoFabricante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_TodoFabricante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_TodoFabricante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnModificaFabricante;
    private javax.swing.JButton btnMostrarFabricante;
    private javax.swing.JButton btnRegistrarFabricante;
    private javax.swing.JPanel jpMenuFabricante;
    private javax.swing.JLabel lblTitulo1;
    // End of variables declaration//GEN-END:variables
}
