/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectois2;

import java.awt.Image;
import javax.swing.*;

/**
 *
 * @author Daniela Espinosa
 */
public class Frm_TodoProducto extends javax.swing.JFrame {
    
    private Frm_RegistraProducto registraProducto;
    private Frm_MuestraProducto muestraProducto;
    private Frm_ModificaProducto2 modifcaProducto;
    private Frm_EntradaStock entradaStock;
    private Frm_EliminaProducto eliminaProducto;

    public Frm_TodoProducto() {
        initComponents();
        AjustarVentana();
        
    }
    
    private void AjustarVentana(){
        //Centrar Ventana
        this.setLocationRelativeTo(null);  
        
        //Bloquear Tamanio
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTodoProducto = new javax.swing.JPanel();
        lblTitulo1 = new javax.swing.JLabel();
        btnRegistrarProducto = new javax.swing.JButton();
        btnMostrarProductos = new javax.swing.JButton();
        btnModificarProductos = new javax.swing.JButton();
        btnModificarStock = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Menú Productos");

        lblTodoProducto.setBackground(new java.awt.Color(255, 102, 102));

        lblTitulo1.setBackground(new java.awt.Color(255, 255, 255));
        lblTitulo1.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 36)); // NOI18N
        lblTitulo1.setForeground(new java.awt.Color(12, 148, 99));
        lblTitulo1.setText("Menú Productos");

        btnRegistrarProducto.setBackground(new java.awt.Color(251, 227, 185));
        btnRegistrarProducto.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btnRegistrarProducto.setText("Registrar Producto");
        btnRegistrarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarProductoActionPerformed(evt);
            }
        });

        btnMostrarProductos.setBackground(new java.awt.Color(251, 227, 185));
        btnMostrarProductos.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btnMostrarProductos.setText("Mostrar Productos");
        btnMostrarProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarProductosActionPerformed(evt);
            }
        });

        btnModificarProductos.setBackground(new java.awt.Color(251, 227, 185));
        btnModificarProductos.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btnModificarProductos.setText("Modificar Productos");
        btnModificarProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarProductosActionPerformed(evt);
            }
        });

        btnModificarStock.setBackground(new java.awt.Color(251, 227, 185));
        btnModificarStock.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btnModificarStock.setText("Modificar Stock");
        btnModificarStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarStockActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout lblTodoProductoLayout = new javax.swing.GroupLayout(lblTodoProducto);
        lblTodoProducto.setLayout(lblTodoProductoLayout);
        lblTodoProductoLayout.setHorizontalGroup(
            lblTodoProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblTodoProductoLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(lblTitulo1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblTodoProductoLayout.createSequentialGroup()
                .addContainerGap(131, Short.MAX_VALUE)
                .addGroup(lblTodoProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnModificarProductos)
                    .addComponent(btnModificarStock, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMostrarProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistrarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(131, 131, 131))
        );
        lblTodoProductoLayout.setVerticalGroup(
            lblTodoProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblTodoProductoLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(lblTitulo1)
                .addGap(44, 44, 44)
                .addComponent(btnRegistrarProducto)
                .addGap(45, 45, 45)
                .addComponent(btnMostrarProductos)
                .addGap(45, 45, 45)
                .addComponent(btnModificarProductos)
                .addGap(45, 45, 45)
                .addComponent(btnModificarStock)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTodoProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTodoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarProductoActionPerformed
        // TODO add your handling code here:
        registraProducto = new Frm_RegistraProducto();
        registraProducto.setVisible(true);
    }//GEN-LAST:event_btnRegistrarProductoActionPerformed

    private void btnMostrarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarProductosActionPerformed
        // TODO add your handling code here:
        muestraProducto = new Frm_MuestraProducto();
        muestraProducto.setVisible(true);
    }//GEN-LAST:event_btnMostrarProductosActionPerformed

    private void btnModificarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarProductosActionPerformed
        // TODO add your handling code here:
        modifcaProducto = new Frm_ModificaProducto2();
        modifcaProducto.setVisible(true);
    }//GEN-LAST:event_btnModificarProductosActionPerformed

    private void btnModificarStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarStockActionPerformed
        // TODO add your handling code here:
        entradaStock = new Frm_EntradaStock();
        entradaStock.setVisible(true);
    }//GEN-LAST:event_btnModificarStockActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_TodoProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_TodoProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_TodoProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_TodoProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_TodoProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnModificarProductos;
    private javax.swing.JButton btnModificarStock;
    private javax.swing.JButton btnMostrarProductos;
    private javax.swing.JButton btnRegistrarProducto;
    private javax.swing.JLabel lblTitulo1;
    private javax.swing.JPanel lblTodoProducto;
    // End of variables declaration//GEN-END:variables
}
