/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectois2;

import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Daniela Espinosa
 */
public class Frm_ActualizaDatosCliente extends javax.swing.JFrame {

    /**
     * Creates new form Frm_ModificaCliente
     */
    public Frm_ActualizaDatosCliente() {
        initComponents();
        AjustarVentana();
        Limpiar();
        RecuperaDatos();
    }
    
    private void AjustarVentana(){
        //Centrar Ventana
        this.setLocationRelativeTo(null);  
        
        //Bloquear Tamanio
        this.setResizable(false);
    }
    
    private void Limpiar(){
        txtNombreModificaCliente.setText("");
        txtApellidosModificaCliente.setText("");
        txtDireccionModificaCliente.setText("");
        txtTelefonoModificaCliente.setText("");
    }
    
    private void RecuperaDatos(){
        try{
            AccesoBD bd = new AccesoBD();
            bd.conectaBD();
            String sql = "SELECT nombres, apellidos, direccion, telefono FROM cliente "
                + "WHERE cedula = '" + ProyectoIS2._Ced + "'"; 
            Statement sta = bd.getConexion().createStatement();
            ResultSet rs= sta.executeQuery(sql);

            while(rs.next()){
                txtNombreModificaCliente.setText(rs.getString("nombres"));
                txtApellidosModificaCliente.setText(rs.getString("apellidos"));
                txtDireccionModificaCliente.setText(rs.getString("direccion"));
                txtTelefonoModificaCliente.setText(rs.getString("telefono"));
            }
                
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e.toString(), "", JOptionPane.INFORMATION_MESSAGE);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpModifcaDatosCliente = new javax.swing.JPanel();
        lblNombreModificaCliente = new javax.swing.JLabel();
        lblApellidosModificaCliente = new javax.swing.JLabel();
        lblDireccionModificaCliente = new javax.swing.JLabel();
        lblTelefonoModificaCliente = new javax.swing.JLabel();
        txtNombreModificaCliente = new javax.swing.JTextField();
        txtApellidosModificaCliente = new javax.swing.JTextField();
        txtDireccionModificaCliente = new javax.swing.JTextField();
        txtTelefonoModificaCliente = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnGuadarModificaCliente = new javax.swing.JButton();
        btnCancelarModificaCliente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Actualización Cliente");

        jpModifcaDatosCliente.setBackground(new java.awt.Color(255, 241, 207));

        lblNombreModificaCliente.setFont(new java.awt.Font("Bauhaus 93", 1, 24)); // NOI18N
        lblNombreModificaCliente.setForeground(new java.awt.Color(38, 63, 68));
        lblNombreModificaCliente.setText("Nombres:");

        lblApellidosModificaCliente.setFont(new java.awt.Font("Bauhaus 93", 1, 24)); // NOI18N
        lblApellidosModificaCliente.setForeground(new java.awt.Color(38, 63, 68));
        lblApellidosModificaCliente.setText("Apellidos:");

        lblDireccionModificaCliente.setFont(new java.awt.Font("Bauhaus 93", 1, 24)); // NOI18N
        lblDireccionModificaCliente.setForeground(new java.awt.Color(38, 63, 68));
        lblDireccionModificaCliente.setText("Dirección:");

        lblTelefonoModificaCliente.setFont(new java.awt.Font("Bauhaus 93", 1, 24)); // NOI18N
        lblTelefonoModificaCliente.setForeground(new java.awt.Color(38, 63, 68));
        lblTelefonoModificaCliente.setText("Teléfono:");

        txtTelefonoModificaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoModificaClienteActionPerformed(evt);
            }
        });
        txtTelefonoModificaCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoModificaClienteKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(38, 63, 68));
        jLabel5.setText("Modifica Clientes");

        btnGuadarModificaCliente.setBackground(new java.awt.Color(255, 211, 105));
        btnGuadarModificaCliente.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btnGuadarModificaCliente.setForeground(new java.awt.Color(1, 86, 104));
        btnGuadarModificaCliente.setText("Guardar");
        btnGuadarModificaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuadarModificaClienteActionPerformed(evt);
            }
        });

        btnCancelarModificaCliente.setBackground(new java.awt.Color(255, 211, 105));
        btnCancelarModificaCliente.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btnCancelarModificaCliente.setForeground(new java.awt.Color(1, 86, 104));
        btnCancelarModificaCliente.setText("Cancelar");
        btnCancelarModificaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarModificaClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpModifcaDatosClienteLayout = new javax.swing.GroupLayout(jpModifcaDatosCliente);
        jpModifcaDatosCliente.setLayout(jpModifcaDatosClienteLayout);
        jpModifcaDatosClienteLayout.setHorizontalGroup(
            jpModifcaDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpModifcaDatosClienteLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(btnGuadarModificaCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelarModificaCliente)
                .addGap(70, 70, 70))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpModifcaDatosClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpModifcaDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpModifcaDatosClienteLayout.createSequentialGroup()
                        .addGap(0, 75, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(97, 97, 97))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpModifcaDatosClienteLayout.createSequentialGroup()
                        .addComponent(lblNombreModificaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jpModifcaDatosClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpModifcaDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblApellidosModificaCliente)
                    .addComponent(lblDireccionModificaCliente)
                    .addComponent(lblTelefonoModificaCliente))
                .addGap(41, 41, 41)
                .addGroup(jpModifcaDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTelefonoModificaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreModificaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellidosModificaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDireccionModificaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpModifcaDatosClienteLayout.setVerticalGroup(
            jpModifcaDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpModifcaDatosClienteLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel5)
                .addGap(45, 45, 45)
                .addGroup(jpModifcaDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreModificaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombreModificaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jpModifcaDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApellidosModificaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellidosModificaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jpModifcaDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDireccionModificaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDireccionModificaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jpModifcaDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefonoModificaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefonoModificaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(jpModifcaDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarModificaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuadarModificaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpModifcaDatosCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpModifcaDatosCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarModificaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarModificaClienteActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_btnCancelarModificaClienteActionPerformed

    private void txtTelefonoModificaClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoModificaClienteKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();

        if((c<'0' || c>'9') && (c != KeyEvent.VK_BACK_SPACE)){
            evt.consume();
            JOptionPane.showMessageDialog(null, "Solo se aceptan números enteros"
                + " positvos...!!!", "", JOptionPane.WARNING_MESSAGE);
        }
        if(txtTelefonoModificaCliente.getText().length()==10){
            evt.consume();
            JOptionPane.showMessageDialog(null, "El TELÉFONO solo debe "
                + "tener máximo 10 dígitos!!!", "", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_txtTelefonoModificaClienteKeyTyped

    private void btnGuadarModificaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuadarModificaClienteActionPerformed
        // TODO add your handling code here:
        Cliente c;
        String _cedula = ProyectoIS2._Ced; 
        boolean pass = false, pass2 = false, pass3 = false, pass4 = false;

        //Validaciones del campo de texto Nombres
        do{
            if(txtNombreModificaCliente.getText().equals("")){
                JOptionPane.showMessageDialog(null,"El campo NOMBRES no debe estar vacío...!!!",
                    "",JOptionPane.WARNING_MESSAGE);
                txtNombreModificaCliente.requestFocus();
                return;
            }
            else{
                pass = true;
            }
        }while(!pass);

        //Validaciones del campo de texto Apellidos
        do{
            if(txtApellidosModificaCliente.getText().equals("")){
                JOptionPane.showMessageDialog(null,"El campo APELLIDOS no debe estar vacío...!!!",
                    "",JOptionPane.WARNING_MESSAGE);
                txtApellidosModificaCliente.requestFocus();
                return;
            }
            else{
                pass2 = true;
            }
        }while(!pass2);

        //Validaciones del campo de texto Dirección
        do{
            if(txtDireccionModificaCliente.getText().equals("")){
                JOptionPane.showMessageDialog(null,"El campo DIRECCIÓN no debe estar vacío...!!!",
                    "",JOptionPane.WARNING_MESSAGE);
                txtDireccionModificaCliente.requestFocus();
                return;
            }            
            else{
                pass3 = true;
            }
        }while(!pass3);
        
        //Validaciones del campo de texto Teléfono
        do{
            if(txtTelefonoModificaCliente.getText().equals("")){
                JOptionPane.showMessageDialog(null,"El campo TELÉFONO no debe estar vacío...!!!",
                    "",JOptionPane.WARNING_MESSAGE);
                txtTelefonoModificaCliente.requestFocus();
                return;
            }
            else if(txtTelefonoModificaCliente.getText().length()<9){
                JOptionPane.showMessageDialog(null,"EL TELÉFONO debe tener al menos 9 dígitos...!!!"
                    ,"",JOptionPane.WARNING_MESSAGE);
                //txtClienteTelefono.setText("");
                txtTelefonoModificaCliente.requestFocus();
                return;
            }
            else{
                pass4 = true;
            }
        }while(!pass4);

        c = new Cliente("", txtNombreModificaCliente.getText(),
            txtApellidosModificaCliente.getText(), txtDireccionModificaCliente.getText(),
            txtTelefonoModificaCliente.getText());
        try {
            c.modificaCliente(_cedula);
        } catch (Exception ex) {

        }
        Limpiar();
        JOptionPane.showMessageDialog(null, "Datos de CLIENTE modificados con éxito!!!"
            , "", JOptionPane.INFORMATION_MESSAGE);
        setVisible(false);
    }//GEN-LAST:event_btnGuadarModificaClienteActionPerformed

    private void txtTelefonoModificaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoModificaClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoModificaClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_ActualizaDatosCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_ActualizaDatosCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_ActualizaDatosCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_ActualizaDatosCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_ActualizaDatosCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarModificaCliente;
    private javax.swing.JButton btnGuadarModificaCliente;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jpModifcaDatosCliente;
    private javax.swing.JLabel lblApellidosModificaCliente;
    private javax.swing.JLabel lblDireccionModificaCliente;
    private javax.swing.JLabel lblNombreModificaCliente;
    private javax.swing.JLabel lblTelefonoModificaCliente;
    private javax.swing.JTextField txtApellidosModificaCliente;
    private javax.swing.JTextField txtDireccionModificaCliente;
    private javax.swing.JTextField txtNombreModificaCliente;
    private javax.swing.JTextField txtTelefonoModificaCliente;
    // End of variables declaration//GEN-END:variables
}
