/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectois2;

import javax.swing.JOptionPane;

/**
 *
 * @author Daniela Espinosa
 */
public class Frm_RegistraFabricante extends javax.swing.JFrame {

    /**
     * Creates new form Frm_RegistraFabricante
     */
    public Frm_RegistraFabricante() {
        initComponents();
        AjustarVentana();
    }
    
    private void Limpiar(){
        txtIngresoFabricanteProducto.setText("");
    }

    private void AjustarVentana(){
        //Centrar Ventana
        this.setLocationRelativeTo(null);  
        
        //Bloquear Tamanio
        this.setResizable(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpRegistraFabricante = new javax.swing.JPanel();
        lblIngresoMarcaProducto = new javax.swing.JLabel();
        bntIngresoProductosGuardar = new javax.swing.JButton();
        bntIngresoProductosCancelar = new javax.swing.JButton();
        lblRegistrarProductos = new javax.swing.JLabel();
        txtIngresoFabricanteProducto = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registrar Fabricante");

        jpRegistraFabricante.setBackground(new java.awt.Color(242, 230, 53));

        lblIngresoMarcaProducto.setFont(new java.awt.Font("Bauhaus 93", 1, 24)); // NOI18N
        lblIngresoMarcaProducto.setForeground(new java.awt.Color(110, 13, 37));
        lblIngresoMarcaProducto.setText("Fabricante:");
        lblIngresoMarcaProducto.setMaximumSize(new java.awt.Dimension(95, 45));
        lblIngresoMarcaProducto.setMinimumSize(new java.awt.Dimension(95, 45));
        lblIngresoMarcaProducto.setPreferredSize(new java.awt.Dimension(95, 45));

        bntIngresoProductosGuardar.setBackground(new java.awt.Color(241, 235, 228));
        bntIngresoProductosGuardar.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        bntIngresoProductosGuardar.setForeground(new java.awt.Color(167, 152, 139));
        bntIngresoProductosGuardar.setText("Guardar");
        bntIngresoProductosGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntIngresoProductosGuardarActionPerformed(evt);
            }
        });

        bntIngresoProductosCancelar.setBackground(new java.awt.Color(241, 235, 228));
        bntIngresoProductosCancelar.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        bntIngresoProductosCancelar.setForeground(new java.awt.Color(167, 152, 139));
        bntIngresoProductosCancelar.setText("Cancelar");
        bntIngresoProductosCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntIngresoProductosCancelarActionPerformed(evt);
            }
        });

        lblRegistrarProductos.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 36)); // NOI18N
        lblRegistrarProductos.setForeground(new java.awt.Color(110, 13, 37));
        lblRegistrarProductos.setText("Registrar Fabricante");

        txtIngresoFabricanteProducto.setPreferredSize(new java.awt.Dimension(95, 45));

        javax.swing.GroupLayout jpRegistraFabricanteLayout = new javax.swing.GroupLayout(jpRegistraFabricante);
        jpRegistraFabricante.setLayout(jpRegistraFabricanteLayout);
        jpRegistraFabricanteLayout.setHorizontalGroup(
            jpRegistraFabricanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpRegistraFabricanteLayout.createSequentialGroup()
                .addGroup(jpRegistraFabricanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpRegistraFabricanteLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblIngresoMarcaProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpRegistraFabricanteLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(bntIngresoProductosGuardar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpRegistraFabricanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpRegistraFabricanteLayout.createSequentialGroup()
                        .addComponent(bntIngresoProductosCancelar)
                        .addGap(58, 58, 58))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpRegistraFabricanteLayout.createSequentialGroup()
                        .addComponent(txtIngresoFabricanteProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpRegistraFabricanteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblRegistrarProductos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpRegistraFabricanteLayout.setVerticalGroup(
            jpRegistraFabricanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpRegistraFabricanteLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(lblRegistrarProductos)
                .addGap(45, 45, 45)
                .addGroup(jpRegistraFabricanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIngresoMarcaProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIngresoFabricanteProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jpRegistraFabricanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntIngresoProductosGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntIngresoProductosCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpRegistraFabricante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpRegistraFabricante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntIngresoProductosCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntIngresoProductosCancelarActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_bntIngresoProductosCancelarActionPerformed

    private void bntIngresoProductosGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntIngresoProductosGuardarActionPerformed
        Fabricante f;
        boolean pass = false;

        //Validaciones del campo de texto Fabricante
        do{
            if(txtIngresoFabricanteProducto.getText().equals("")){
                JOptionPane.showMessageDialog(null,"El campo FABRICANTE no debe estar vacío...!!!",
                    "",JOptionPane.WARNING_MESSAGE);
                txtIngresoFabricanteProducto.requestFocus();
                return;
            }
            else{
                pass = true;
            }
        }while(!pass);
        
        f = new Fabricante(txtIngresoFabricanteProducto.getText());

        try {
            f.insertaFabricante();
        } catch (Exception e) {
            System.out.println(e.toString());
        }
       

        Limpiar();
        JOptionPane.showMessageDialog(null, "Fabricante agregado a la base de datos éxito!!!"
            , "", JOptionPane.INFORMATION_MESSAGE);
        setVisible(false);
    }//GEN-LAST:event_bntIngresoProductosGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_RegistraFabricante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_RegistraFabricante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_RegistraFabricante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_RegistraFabricante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_RegistraFabricante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntIngresoProductosCancelar;
    private javax.swing.JButton bntIngresoProductosGuardar;
    private javax.swing.JPanel jpRegistraFabricante;
    private javax.swing.JLabel lblIngresoMarcaProducto;
    private javax.swing.JLabel lblRegistrarProductos;
    private javax.swing.JTextField txtIngresoFabricanteProducto;
    // End of variables declaration//GEN-END:variables
}
