
package proyectois2;

import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Daniela Espinosa
 */
public class Frm_ModificaProducto2 extends javax.swing.JFrame {
    
    private Frm_ActualizaDatosProducto ActualizaDatosProducto;
    DefaultTableModel model;

    /**
     * Creates new form Frm_ModificaProducto2
     */
    public Frm_ModificaProducto2() {
        initComponents();
        AjustarVentana();
        try {
            actualizarTabla();
        } catch (Exception ex) {
            
        }
    }
    
    private void AjustarVentana(){
        //Centrar Ventana
        this.setLocationRelativeTo(null);  
        
        //Bloquear Tamanio
        this.setResizable(false);
    }
    
    public final void actualizarTabla() throws Exception{
    DefaultTableModel modelo = new DefaultTableModel();
        AccesoBD bd = new AccesoBD();
        ResultSet rs = bd.getTabla("SELECT codigo, stock, descripcion, precio FROM articulo");
        modelo.setColumnIdentifiers(new Object[]{"Código", "Stock", "Descripción", "Precio"});
        try{
            while(rs.next()){
                modelo.addRow(new Object[]{rs.getString("codigo"), rs.getInt("stock"),
                rs.getString("descripcion"), rs.getDouble("precio")});
            }
            jtMuestraProductosParaModificar.setModel(modelo);
        }
        catch(SQLException e){
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpModificaProducto = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtMuestraProductosParaModificar = new javax.swing.JTable();
        btnBuscaModificaProducto = new javax.swing.JButton();
        txtCodigoaBuscarModifica = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modificar Producto");

        jpModificaProducto.setBackground(new java.awt.Color(255, 102, 102));

        jtMuestraProductosParaModificar = new javax.swing.JTable(){
            public boolean isCellEditable (int rowIndex, int colIndex){
                return false;
            }
        };
        jtMuestraProductosParaModificar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código", "Cantidad", "Descripción", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtMuestraProductosParaModificar.getTableHeader().setReorderingAllowed(false);
        jtMuestraProductosParaModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtMuestraProductosParaModificarMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtMuestraProductosParaModificar);

        btnBuscaModificaProducto.setBackground(new java.awt.Color(251, 227, 185));
        btnBuscaModificaProducto.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btnBuscaModificaProducto.setText("Modificar");
        btnBuscaModificaProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaModificaProductoActionPerformed(evt);
            }
        });

        txtCodigoaBuscarModifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoaBuscarModificaActionPerformed(evt);
            }
        });
        txtCodigoaBuscarModifica.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodigoaBuscarModificaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoaBuscarModificaKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 102));
        jLabel1.setText("Búsqueda de Producto");

        javax.swing.GroupLayout jpModificaProductoLayout = new javax.swing.GroupLayout(jpModificaProducto);
        jpModificaProducto.setLayout(jpModificaProductoLayout);
        jpModificaProductoLayout.setHorizontalGroup(
            jpModificaProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpModificaProductoLayout.createSequentialGroup()
                .addContainerGap(114, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(81, 81, 81))
            .addGroup(jpModificaProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(jpModificaProductoLayout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addComponent(txtCodigoaBuscarModifica, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(btnBuscaModificaProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpModificaProductoLayout.setVerticalGroup(
            jpModificaProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpModificaProductoLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(jpModificaProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBuscaModificaProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodigoaBuscarModifica, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpModificaProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpModificaProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscaModificaProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaModificaProductoActionPerformed
        // TODO add your handling code here:
        Articulo a = new Articulo(); String _codigo;
        boolean pass = false;
        _codigo = txtCodigoaBuscarModifica.getText();
        ProyectoIS2._Code = _codigo;
        
        do{
            try {
                if(a.verificaCodigo(_codigo)){
                    pass = true;
                    setVisible(false);
                    ActualizaDatosProducto = new Frm_ActualizaDatosProducto();
                    ActualizaDatosProducto.setVisible(true);                   
                }
                else if(txtCodigoaBuscarModifica.getText().equals("")){
                    JOptionPane.showMessageDialog(null, "El CÓDIGO ingresado no se encuentra"
                        + " registrado, ingrese uno valido o escoja uno de los que se muestran en la tabla...", "ATENCIÓN",
                        JOptionPane.INFORMATION_MESSAGE);
                    txtCodigoaBuscarModifica.setText("");
                    return;
                }
                else{
                    JOptionPane.showMessageDialog(null, "El CÓDIGO ingresado no se encuentra"
                        + " registrado, ingrese uno valido o escoja uno de los que se muestran en la tabla...", "ATENCIÓN",
                        JOptionPane.INFORMATION_MESSAGE);
                    txtCodigoaBuscarModifica.setText("");
                    return;
                }
            } catch (Exception e) {
            
            }
        }while(!pass);
    }//GEN-LAST:event_btnBuscaModificaProductoActionPerformed

    private void txtCodigoaBuscarModificaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoaBuscarModificaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoaBuscarModificaKeyTyped

    private void txtCodigoaBuscarModificaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoaBuscarModificaKeyPressed
        // TODO add your handling code here
        AccesoBD bd = new AccesoBD();
        String[] Titulos = {"Código", "Stock", "Descripcion", "Precio"};
        String[] Registro = new String[50];
        
        String sql = "SELECT * FROM articulo WHERE codigo LIKE '%" + txtCodigoaBuscarModifica.getText()+ "%'"
            + "OR stock LIKE '%" + txtCodigoaBuscarModifica.getText() + "%'"
            + "OR descripcion LIKE '%" + txtCodigoaBuscarModifica.getText() + "%'"
            + "OR precio LIKE '%" + txtCodigoaBuscarModifica.getText() + "%'";
        
        model = new DefaultTableModel(null,Titulos);
        try {
            bd.conectaBD();
            Statement sta = bd.getConexion().createStatement();
            ResultSet rs= sta.executeQuery(sql);
            
            while(rs.next()){
                Registro[0] = rs.getString("codigo");
                Registro[1] = rs.getString("stock");
                Registro[2] = rs.getString("descripcion");
                Registro[3] = rs.getString("precio");
                model.addRow(Registro);
            }
            jtMuestraProductosParaModificar.setModel(model);
        } catch (Exception ex) {
            
        }
    }//GEN-LAST:event_txtCodigoaBuscarModificaKeyPressed

    private void jtMuestraProductosParaModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtMuestraProductosParaModificarMouseClicked
        // TODO add your handling code here:
        int col = jtMuestraProductosParaModificar.getSelectedRow();
        
        txtCodigoaBuscarModifica.setText(jtMuestraProductosParaModificar.getModel().
                getValueAt(col, 0).toString());
    }//GEN-LAST:event_jtMuestraProductosParaModificarMouseClicked

    private void txtCodigoaBuscarModificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoaBuscarModificaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoaBuscarModificaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_ModificaProducto2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_ModificaProducto2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_ModificaProducto2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_ModificaProducto2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_ModificaProducto2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscaModificaProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel jpModificaProducto;
    private javax.swing.JTable jtMuestraProductosParaModificar;
    private javax.swing.JTextField txtCodigoaBuscarModifica;
    // End of variables declaration//GEN-END:variables
}
