package proyectois2;

import java.awt.*;
import javax.swing.*;

/**
 *
 * @author Daniela Espinosa
 */
public class Frm_MenuPrincipal extends javax.swing.JFrame {
    
    private Frm_TodoProducto todoProducto;
    private Frm_TodoFabricante todoFabricante;
    private Frm_TodoCliente todoCliente;
    private Frm_TodoVenta todoVenta;
    
    public Frm_MenuPrincipal() {
        initComponents();
        AjustarImagen(lblFondo);
        AjustarVentana();
    }

    private void AjustarImagen(JLabel lbl){
        ImageIcon imagen = new ImageIcon("src/imagenes/Gradient.jpg");
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(
            lbl.getWidth(), lbl.getHeight(), Image.SCALE_DEFAULT));
        lbl.setIcon(icono);
        this.repaint();
    }
     
    private void AjustarVentana(){
        //Centrar Ventana
        this.setLocationRelativeTo(null);  
        
        //Bloquear Tamanio
        this.setResizable(false);
    }
           
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lblTitulo2 = new javax.swing.JLabel();
        btnPanelProductos = new javax.swing.JButton();
        btnPanelFabricantes = new javax.swing.JButton();
        btnPanelVentas = new javax.swing.JButton();
        btnPanelClientes = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menú Principal");

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo2.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 36)); // NOI18N
        lblTitulo2.setForeground(new java.awt.Color(220, 20, 60));
        lblTitulo2.setText("Proyecto BD");
        jPanel2.add(lblTitulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 109, -1, 50));

        btnPanelProductos.setBackground(new java.awt.Color(139, 69, 19));
        btnPanelProductos.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btnPanelProductos.setForeground(new java.awt.Color(255, 250, 240));
        btnPanelProductos.setText("Panel Productos");
        btnPanelProductos.setToolTipText("");
        btnPanelProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPanelProductosActionPerformed(evt);
            }
        });
        jPanel2.add(btnPanelProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 235, -1));

        btnPanelFabricantes.setBackground(new java.awt.Color(139, 69, 19));
        btnPanelFabricantes.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btnPanelFabricantes.setForeground(new java.awt.Color(255, 250, 240));
        btnPanelFabricantes.setText("Panel Fabricantes");
        btnPanelFabricantes.setToolTipText("");
        btnPanelFabricantes.setMaximumSize(new java.awt.Dimension(200, 35));
        btnPanelFabricantes.setMinimumSize(new java.awt.Dimension(200, 35));
        btnPanelFabricantes.setPreferredSize(new java.awt.Dimension(200, 35));
        btnPanelFabricantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPanelFabricantesActionPerformed(evt);
            }
        });
        jPanel2.add(btnPanelFabricantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 235, -1));

        btnPanelVentas.setBackground(new java.awt.Color(139, 69, 19));
        btnPanelVentas.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btnPanelVentas.setForeground(new java.awt.Color(255, 250, 240));
        btnPanelVentas.setText("Panel Ventas");
        btnPanelVentas.setToolTipText("");
        btnPanelVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPanelVentasActionPerformed(evt);
            }
        });
        jPanel2.add(btnPanelVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, 235, -1));

        btnPanelClientes.setBackground(new java.awt.Color(139, 69, 19));
        btnPanelClientes.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btnPanelClientes.setForeground(new java.awt.Color(255, 250, 240));
        btnPanelClientes.setText("Panel Clientes");
        btnPanelClientes.setToolTipText("");
        btnPanelClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPanelClientesActionPerformed(evt);
            }
        });
        jPanel2.add(btnPanelClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 235, -1));
        jPanel2.add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, -2, 580, 510));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPanelVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPanelVentasActionPerformed
        // TODO add your handling code here:
        todoVenta = new Frm_TodoVenta();
        todoVenta.setVisible(true);
    }//GEN-LAST:event_btnPanelVentasActionPerformed

    private void btnPanelFabricantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPanelFabricantesActionPerformed
        // TODO add your handling code here:
        todoFabricante = new Frm_TodoFabricante();
        todoFabricante.setVisible(true);
    }//GEN-LAST:event_btnPanelFabricantesActionPerformed

    private void btnPanelProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPanelProductosActionPerformed
        // TODO add your handling code here:
        todoProducto = new Frm_TodoProducto();
        todoProducto.setVisible(true);
    }//GEN-LAST:event_btnPanelProductosActionPerformed

    private void btnPanelClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPanelClientesActionPerformed
        // TODO add your handling code here:
        todoCliente = new Frm_TodoCliente();
        todoCliente.setVisible(true);
    }//GEN-LAST:event_btnPanelClientesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPanelClientes;
    private javax.swing.JButton btnPanelFabricantes;
    private javax.swing.JButton btnPanelProductos;
    private javax.swing.JButton btnPanelVentas;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblTitulo2;
    // End of variables declaration//GEN-END:variables
}
