/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectois2;

import javax.swing.table.DefaultTableModel;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Daniela Espinosa
 */
public class Frm_EliminaProducto extends javax.swing.JFrame {
    DefaultTableModel model;
    private Frm_ConfirmaEliminar confirmaEliminar;

    /**
     * Creates new form Frm_EliminaProducto
     */
    public Frm_EliminaProducto() {
        initComponents();
        try{
            actualizarTabla();
        }catch(Exception e){
            
        }
    }

    public final void actualizarTabla() throws Exception{
    DefaultTableModel modelo = new DefaultTableModel();
        AccesoBD bd = new AccesoBD();
        ResultSet rs = bd.getTabla("SELECT codigo, cantidad, descripcion, precio FROM articulo");
        modelo.setColumnIdentifiers(new Object[]{"Código", "Cantidad", "Descripción", "Precio"});
        try{
            while(rs.next()){
                modelo.addRow(new Object[]{rs.getString("codigo"), rs.getInt("cantidad"),
                rs.getString("descripcion"), rs.getDouble("precio")});
            }
            jtMuestraProductos.setModel(modelo);
        }
        catch(SQLException e){
            System.out.println(e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpEliminaProducto = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtMuestraProductos = new javax.swing.JTable();
        txtBuscaProducto = new javax.swing.JTextField();
        lblTitulo2 = new javax.swing.JLabel();
        lblTitulo1 = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jtMuestraProductos = new javax.swing.JTable(){
            public boolean isCellEditable (int rowIndex, int colIndex){
                return false;
            }
        };
        jtMuestraProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtMuestraProductos.getTableHeader().setReorderingAllowed(false);
        jtMuestraProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtMuestraProductosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtMuestraProductos);

        txtBuscaProducto.setPreferredSize(new java.awt.Dimension(6, 45));
        txtBuscaProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscaProductoActionPerformed(evt);
            }
        });
        txtBuscaProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscaProductoKeyPressed(evt);
            }
        });

        lblTitulo2.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 13)); // NOI18N
        lblTitulo2.setForeground(new java.awt.Color(255, 51, 51));
        lblTitulo2.setText("Seleccione el producto a eliminar:");
        lblTitulo2.setPreferredSize(new java.awt.Dimension(34, 40));

        lblTitulo1.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 36)); // NOI18N
        lblTitulo1.setForeground(new java.awt.Color(102, 0, 102));
        lblTitulo1.setText("Inventario de Productos");

        btnEliminar.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 0));
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpEliminaProductoLayout = new javax.swing.GroupLayout(jpEliminaProducto);
        jpEliminaProducto.setLayout(jpEliminaProductoLayout);
        jpEliminaProductoLayout.setHorizontalGroup(
            jpEliminaProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEliminaProductoLayout.createSequentialGroup()
                .addGroup(jpEliminaProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpEliminaProductoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTitulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscaProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpEliminaProductoLayout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(lblTitulo1)))
                .addGap(0, 14, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpEliminaProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addGap(21, 21, 21))
        );
        jpEliminaProductoLayout.setVerticalGroup(
            jpEliminaProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpEliminaProductoLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(lblTitulo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(jpEliminaProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jpEliminaProductoLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jpEliminaProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTitulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtBuscaProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpEliminaProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpEliminaProducto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscaProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscaProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscaProductoActionPerformed

    private void txtBuscaProductoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscaProductoKeyPressed
        // TODO add your handling code here:
        AccesoBD bd = new AccesoBD();
        String[] Titulos = {"Código", "Cantidad", "Descripcion", "Precio"};
        String[] Registro = new String[50];

        String sql = "SELECT * FROM articulo WHERE codigo LIKE '%" + txtBuscaProducto.getText()+ "%'"
        + "OR cantidad LIKE '%" + txtBuscaProducto.getText() + "%'"
        + "OR descripcion LIKE '%" + txtBuscaProducto.getText() + "%'"
        + "OR precio LIKE '%" + txtBuscaProducto.getText() + "%'";

        model = new DefaultTableModel(null,Titulos);
        try {
            bd.conectaBD();
            Statement sta = bd.getConexion().createStatement();
            ResultSet rs= sta.executeQuery(sql);

            while(rs.next()){
                Registro[0] = rs.getString("codigo");
                Registro[1] = rs.getString("cantidad");
                Registro[2] = rs.getString("descripcion");
                Registro[3] = rs.getString("precio");
                model.addRow(Registro);
            }
            jtMuestraProductos.setModel(model);
        } catch (Exception ex) {

        }
    }//GEN-LAST:event_txtBuscaProductoKeyPressed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        Articulo a = new Articulo();
        try{
            if(a.verificaCodigo(txtBuscaProducto.getText())){
                ProyectoIS2._Code = txtBuscaProducto.getText();
                confirmaEliminar = new Frm_ConfirmaEliminar();
                confirmaEliminar.setVisible(true);
                setVisible(false);
            }
            else{
                JOptionPane.showMessageDialog(null, "Codigo Invalido... Ingrese uno de los "
                        + "que estan en la tabla", "", JOptionPane.WARNING_MESSAGE);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Ingrese un codigo valido...!!!", "", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void jtMuestraProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtMuestraProductosMouseClicked
        // TODO add your handling code here:
        int col = jtMuestraProductos.getSelectedRow();
        
        txtBuscaProducto.setText(jtMuestraProductos.getModel().
                getValueAt(col, 0).toString());
    }//GEN-LAST:event_jtMuestraProductosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_EliminaProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_EliminaProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_EliminaProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_EliminaProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_EliminaProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpEliminaProducto;
    private javax.swing.JTable jtMuestraProductos;
    private javax.swing.JLabel lblTitulo1;
    private javax.swing.JLabel lblTitulo2;
    private javax.swing.JTextField txtBuscaProducto;
    // End of variables declaration//GEN-END:variables
}
