
package proyectois2;


import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Daniela Espinosa
 */
public class Frm_ActualizaDatosProducto extends javax.swing.JFrame {

    /**
     * Creates new form Frm_ActualizaDatosProducto
     */
    public Frm_ActualizaDatosProducto() {
        initComponents();
        AjustarVentana();
        RecuperaDatos();
    }
    
    private void AjustarVentana(){
        //Centrar Ventana
        this.setLocationRelativeTo(null);  
        
        //Bloquear Tamanio
        this.setResizable(false);
    }
    
    private void RecuperaDatos(){
        try{
            AccesoBD bd = new AccesoBD();
            bd.conectaBD();
            String sql = "SELECT stock, descripcion, precio FROM articulo "
                + "WHERE codigo = '" + ProyectoIS2._Code + "'"; 
            Statement sta = bd.getConexion().createStatement();
            ResultSet rs= sta.executeQuery(sql);

            while(rs.next()){
                txtModificaNombreProducto.setText(rs.getString("descripcion"));
                txtModificaStockProducto.setText(rs.getString("stock"));
                txtModificaCostoProducto.setText(rs.getString("precio"));
            }
                
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e.toString(), "", JOptionPane.INFORMATION_MESSAGE);
        }
        
    }
    
    public void Limpiar(){
        txtModificaNombreProducto.setText("");
        txtModificaCostoProducto.setText("");
        txtModificaStockProducto.setText("");       
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpActualizaDatosProducto = new javax.swing.JPanel();
        txtModificaStockProducto = new javax.swing.JTextField();
        bntModificaProductosGuardar = new javax.swing.JButton();
        bntModificaProductosCancelar = new javax.swing.JButton();
        lblModificaCostoProducto = new javax.swing.JLabel();
        lblModificaStockProducto = new javax.swing.JLabel();
        lblModificaNombreProducto = new javax.swing.JLabel();
        txtModificaNombreProducto = new javax.swing.JTextField();
        txtModificaCostoProducto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Actualización Producto");

        jpActualizaDatosProducto.setBackground(new java.awt.Color(255, 102, 102));

        txtModificaStockProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtModificaStockProductoKeyTyped(evt);
            }
        });

        bntModificaProductosGuardar.setBackground(new java.awt.Color(251, 227, 185));
        bntModificaProductosGuardar.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        bntModificaProductosGuardar.setText("Guardar");
        bntModificaProductosGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntModificaProductosGuardarActionPerformed(evt);
            }
        });

        bntModificaProductosCancelar.setBackground(new java.awt.Color(251, 227, 185));
        bntModificaProductosCancelar.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        bntModificaProductosCancelar.setText("Cancelar");
        bntModificaProductosCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntModificaProductosCancelarActionPerformed(evt);
            }
        });

        lblModificaCostoProducto.setBackground(new java.awt.Color(153, 153, 255));
        lblModificaCostoProducto.setFont(new java.awt.Font("Bauhaus 93", 1, 24)); // NOI18N
        lblModificaCostoProducto.setForeground(new java.awt.Color(102, 0, 102));
        lblModificaCostoProducto.setText("Precio:");

        lblModificaStockProducto.setBackground(new java.awt.Color(153, 153, 255));
        lblModificaStockProducto.setFont(new java.awt.Font("Bauhaus 93", 1, 24)); // NOI18N
        lblModificaStockProducto.setForeground(new java.awt.Color(102, 0, 102));
        lblModificaStockProducto.setText("Stock:");

        lblModificaNombreProducto.setBackground(new java.awt.Color(153, 153, 255));
        lblModificaNombreProducto.setFont(new java.awt.Font("Bauhaus 93", 1, 24)); // NOI18N
        lblModificaNombreProducto.setForeground(new java.awt.Color(102, 0, 102));
        lblModificaNombreProducto.setText("Descripción:");

        txtModificaCostoProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtModificaCostoProductoKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 102));
        jLabel1.setText("Actualiza Datos Producto");

        javax.swing.GroupLayout jpActualizaDatosProductoLayout = new javax.swing.GroupLayout(jpActualizaDatosProducto);
        jpActualizaDatosProducto.setLayout(jpActualizaDatosProductoLayout);
        jpActualizaDatosProductoLayout.setHorizontalGroup(
            jpActualizaDatosProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpActualizaDatosProductoLayout.createSequentialGroup()
                .addGroup(jpActualizaDatosProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpActualizaDatosProductoLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(lblModificaNombreProducto)
                        .addGap(76, 76, 76)
                        .addComponent(txtModificaNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpActualizaDatosProductoLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(lblModificaStockProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(365, 365, 365)
                        .addComponent(txtModificaStockProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpActualizaDatosProductoLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(lblModificaCostoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(365, 365, 365)
                        .addComponent(txtModificaCostoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpActualizaDatosProductoLayout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(bntModificaProductosGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(bntModificaProductosCancelar)))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpActualizaDatosProductoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(42, 42, 42))
        );
        jpActualizaDatosProductoLayout.setVerticalGroup(
            jpActualizaDatosProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpActualizaDatosProductoLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addGroup(jpActualizaDatosProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblModificaNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpActualizaDatosProductoLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(txtModificaNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(45, 45, 45)
                .addGroup(jpActualizaDatosProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblModificaStockProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(txtModificaStockProducto))
                .addGroup(jpActualizaDatosProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpActualizaDatosProductoLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(txtModificaCostoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpActualizaDatosProductoLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(lblModificaCostoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(45, 45, 45)
                .addGroup(jpActualizaDatosProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntModificaProductosGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntModificaProductosCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpActualizaDatosProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpActualizaDatosProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntModificaProductosGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntModificaProductosGuardarActionPerformed
        // TODO add your handling code here:
        String _codigo = ProyectoIS2._Code;
        Articulo a = new Articulo();
        boolean pass = false, pass2 = false, pass3 = false, pass4 = false;

        //Validaciones del campo de texto Cantidad
        do{
            if(txtModificaStockProducto.getText().equals("")){
                JOptionPane.showMessageDialog(null,"El campo CANTIDAD no debe estar vacío...!!!",
                    "",JOptionPane.WARNING_MESSAGE);
                txtModificaStockProducto.requestFocus();
                return;
            }
            else if(Integer.parseInt(txtModificaStockProducto.getText())<=0){
                JOptionPane.showMessageDialog(null,"La CANTIDAD no puede ser 0...!!!"
                    ,"",JOptionPane.WARNING_MESSAGE);
                txtModificaStockProducto.setText("");
                txtModificaStockProducto.requestFocus();
                return;
            }
            else{
                pass2 = true;
            }
        }while(!pass2);
        
        //Validaciones del campo de texto Descripción
        do{
            if(txtModificaNombreProducto.getText().equals("")){
                JOptionPane.showMessageDialog(null,"El campo DESCRIPCIÓN no debe estar vacío...!!!",
                    "",JOptionPane.WARNING_MESSAGE);
                txtModificaNombreProducto.requestFocus();
                return;
            }
            else{
                pass3 = true;
            }
        }while(!pass3);

        //Validaciones del campo de texto Precio
        do{
            if(txtModificaCostoProducto.getText().equals("")){
                JOptionPane.showMessageDialog(null,"El campo PRECIO no debe estar vacío...!!!",
                    "",JOptionPane.WARNING_MESSAGE);
                txtModificaCostoProducto.requestFocus();
                return;
            }
            else if(Double.parseDouble(txtModificaCostoProducto.getText())<=0){
                JOptionPane.showMessageDialog(null,"El PRECIO no puede ser 0...!!!"
                    ,"",JOptionPane.WARNING_MESSAGE);
                txtModificaCostoProducto.setText("");
                txtModificaCostoProducto.requestFocus();
                return;
            }
            else{
                pass4 = true;
            }
        }while(!pass4); 

        a = new Articulo("",Integer.parseInt(txtModificaStockProducto.getText()),0,
            txtModificaNombreProducto.getText(), Double.parseDouble(txtModificaCostoProducto.getText()));
        try {
            a.modificaProducto(_codigo);
        } catch (Exception ex) {
            System.out.println(ex.toString());
        }
        Limpiar();
        JOptionPane.showMessageDialog(null, "Datos del PRODUCTO modificado con éxito!!!"
            , "", JOptionPane.INFORMATION_MESSAGE);
        setVisible(false);
    }//GEN-LAST:event_bntModificaProductosGuardarActionPerformed

    private void bntModificaProductosCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntModificaProductosCancelarActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_bntModificaProductosCancelarActionPerformed

    private void txtModificaCostoProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtModificaCostoProductoKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();

        if((c<'0' || c>'9') && (c != KeyEvent.VK_BACK_SPACE) && (c != '.'||
            txtModificaCostoProducto.getText().contains("."))){
        evt.consume();
        JOptionPane.showMessageDialog(null, "Solo se aceptan numeros enteros "
            + "positivos y un punto decimal !!!","",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_txtModificaCostoProductoKeyTyped

    private void txtModificaStockProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtModificaStockProductoKeyTyped
        // TODO add your handling code here:
                // TODO add your handling code here:
        char c = evt.getKeyChar();

        if((c<'0' || c>'9') && (c != KeyEvent.VK_BACK_SPACE)){
            evt.consume();
            JOptionPane.showMessageDialog(null, "Solo se aceptan numeros enteros"
                + " positvos!!!","",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_txtModificaStockProductoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_ActualizaDatosProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_ActualizaDatosProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_ActualizaDatosProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_ActualizaDatosProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_ActualizaDatosProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntModificaProductosCancelar;
    private javax.swing.JButton bntModificaProductosGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jpActualizaDatosProducto;
    private javax.swing.JLabel lblModificaCostoProducto;
    private javax.swing.JLabel lblModificaNombreProducto;
    private javax.swing.JLabel lblModificaStockProducto;
    private javax.swing.JTextField txtModificaCostoProducto;
    private javax.swing.JTextField txtModificaNombreProducto;
    private javax.swing.JTextField txtModificaStockProducto;
    // End of variables declaration//GEN-END:variables
}
