/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectois2;

import javax.swing.table.DefaultTableModel;
import java.sql.*;

/**
 *
 * @author Daniela Espinosa
 */
public class Frm_MuestraRegistroFacturas extends javax.swing.JFrame {

    DefaultTableModel model;
    
            
    public Frm_MuestraRegistroFacturas() {
        initComponents();
        AjustarVentana();
        try {
            actualizarTabla();
        } catch (Exception ex) {
            
        }
    }
    
    private void AjustarVentana(){
        //Centrar Ventana
        this.setLocationRelativeTo(null);  
        
        //Bloquear Tamanio
        this.setResizable(false);
    }
    
    public final void actualizarTabla() throws Exception{
    DefaultTableModel modelo = new DefaultTableModel();
        AccesoBD bd = new AccesoBD();
        ResultSet rs = bd.getTabla("SELECT num_factura, cedula, nombres, apellidos, "
            + "factura.direccion, telefono, subtotal, iva, (subtotal+iva) FROM factura INNER JOIN cliente " +
            "WHERE factura.cliente_id_cliente = cliente.id_cliente order by num_factura; ");
        modelo.setColumnIdentifiers(new Object[]{"Número Factura", "Cédula", "Nombres", "Apellidos", "Dirección",
        "Teléfono", "SubTotal", "IVA", "Total"});
        try{
            while(rs.next()){
                modelo.addRow(new Object[]{rs.getInt("num_factura"), rs.getString("cedula"),
                rs.getString("nombres"), rs.getString("apellidos"),  rs.getString("direccion"),
                rs.getString("telefono"), rs.getDouble("subtotal"),  rs.getDouble("iva"), rs.getDouble("(subtotal+iva)")
                });
            }
            jtMuestraProductosParaModificar.setModel(modelo);
        }
        catch(SQLException e){
            System.out.println(e.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtMuestraProductosParaModificar = new javax.swing.JTable();
        txtCodigoaBuscarModifica = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro de Facturas");

        jPanel1.setBackground(new java.awt.Color(211, 244, 255));

        jtMuestraProductosParaModificar = new javax.swing.JTable(){
            public boolean isCellEditable (int rowIndex, int colIndex){
                return false;
            }
        };
        jtMuestraProductosParaModificar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Número Factura", "Nombres", "Apellidos", "Dirección", "Teléfono", "SubTotal", "IVA", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtMuestraProductosParaModificar.getTableHeader().setReorderingAllowed(false);
        jtMuestraProductosParaModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtMuestraProductosParaModificarMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtMuestraProductosParaModificar);

        txtCodigoaBuscarModifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoaBuscarModificaActionPerformed(evt);
            }
        });
        txtCodigoaBuscarModifica.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodigoaBuscarModificaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoaBuscarModificaKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(231, 164, 228));
        jLabel1.setText("Registro de Facturas");

        jLabel2.setFont(new java.awt.Font("Bauhaus 93", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(231, 164, 228));
        jLabel2.setText("Buscar:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(35, 35, 35)
                .addComponent(txtCodigoaBuscarModifica, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(346, 346, 346))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 835, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigoaBuscarModifica, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtMuestraProductosParaModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtMuestraProductosParaModificarMouseClicked
        // TODO add your handling code here:
        int col = jtMuestraProductosParaModificar.getSelectedRow();

        txtCodigoaBuscarModifica.setText(jtMuestraProductosParaModificar.getModel().
            getValueAt(col, 0).toString());
    }//GEN-LAST:event_jtMuestraProductosParaModificarMouseClicked

    private void txtCodigoaBuscarModificaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoaBuscarModificaKeyPressed
        
    }//GEN-LAST:event_txtCodigoaBuscarModificaKeyPressed

    private void txtCodigoaBuscarModificaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoaBuscarModificaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoaBuscarModificaKeyTyped

    private void txtCodigoaBuscarModificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoaBuscarModificaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoaBuscarModificaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_MuestraRegistroFacturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_MuestraRegistroFacturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_MuestraRegistroFacturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_MuestraRegistroFacturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_MuestraRegistroFacturas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jtMuestraProductosParaModificar;
    private javax.swing.JTextField txtCodigoaBuscarModifica;
    // End of variables declaration//GEN-END:variables
}
