/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectois2;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Daniela Espinosa
 */
public class Frm_MuestraFabricante extends javax.swing.JFrame {

    /**
     * Creates new form Frm_MuestraFabricante
     */
    DefaultTableModel model;
    
    public Frm_MuestraFabricante() {
        initComponents();
        AjustarVentana();
        try {
            actualizarTabla();
        } catch (Exception ex) {
            Logger.getLogger(Frm_MuestraFabricante.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void AjustarVentana(){
        //Centrar Ventana
        this.setLocationRelativeTo(null);  
        
        //Bloquear Tamanio
        this.setResizable(false);
    }
    
    private void actualizarTabla() throws Exception{
    DefaultTableModel modelo = new DefaultTableModel();
        AccesoBD bd = new AccesoBD();
        ResultSet rs = bd.getTabla("SELECT id_fabricante, nombre_fabricante FROM fabricante");
        modelo.setColumnIdentifiers(new Object[]{"Código", "Nombre Frabricante"});
        try{
            while(rs.next()){
                modelo.addRow(new Object[]{rs.getInt("id_fabricante"), rs.getString("nombre_fabricante")});
            }
            jtMuestraFabricantes.setModel(modelo);
        }
        catch(SQLException e){
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpInventarioFabricantes = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtMuestraFabricantes = new javax.swing.JTable();
        txtBuscaProducto = new javax.swing.JTextField();
        lblTitulo2 = new javax.swing.JLabel();
        lblTitulo1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Inventario de Fabricantes");

        jpInventarioFabricantes.setBackground(new java.awt.Color(242, 230, 53));
        jpInventarioFabricantes.setForeground(new java.awt.Color(110, 13, 37));

        jtMuestraFabricantes = new javax.swing.JTable(){
            public boolean isCellEditable (int rowIndex, int colIndex){
                return false;
            }
        };
        jtMuestraFabricantes.setBackground(new java.awt.Color(242, 230, 53));
        jtMuestraFabricantes.setForeground(new java.awt.Color(110, 13, 37));
        jtMuestraFabricantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtMuestraFabricantes.setGridColor(new java.awt.Color(110, 13, 37));
        jtMuestraFabricantes.setSelectionForeground(new java.awt.Color(110, 13, 37));
        jtMuestraFabricantes.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jtMuestraFabricantes);

        txtBuscaProducto.setPreferredSize(new java.awt.Dimension(6, 45));
        txtBuscaProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscaProductoActionPerformed(evt);
            }
        });
        txtBuscaProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscaProductoKeyPressed(evt);
            }
        });

        lblTitulo2.setFont(new java.awt.Font("Bauhaus 93", 1, 24)); // NOI18N
        lblTitulo2.setForeground(new java.awt.Color(110, 13, 37));
        lblTitulo2.setText("Búsqueda:");
        lblTitulo2.setPreferredSize(new java.awt.Dimension(34, 40));

        lblTitulo1.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 36)); // NOI18N
        lblTitulo1.setForeground(new java.awt.Color(110, 13, 37));
        lblTitulo1.setText("Inventario de Fabricantes");

        javax.swing.GroupLayout jpInventarioFabricantesLayout = new javax.swing.GroupLayout(jpInventarioFabricantes);
        jpInventarioFabricantes.setLayout(jpInventarioFabricantesLayout);
        jpInventarioFabricantesLayout.setHorizontalGroup(
            jpInventarioFabricantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpInventarioFabricantesLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jpInventarioFabricantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpInventarioFabricantesLayout.createSequentialGroup()
                        .addComponent(lblTitulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscaProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(174, 174, 174))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpInventarioFabricantesLayout.createSequentialGroup()
                        .addComponent(lblTitulo1)
                        .addGap(19, 19, 19))))
        );
        jpInventarioFabricantesLayout.setVerticalGroup(
            jpInventarioFabricantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpInventarioFabricantesLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(lblTitulo1)
                .addGap(45, 45, 45)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(jpInventarioFabricantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBuscaProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpInventarioFabricantes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpInventarioFabricantes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscaProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscaProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscaProductoActionPerformed

    private void txtBuscaProductoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscaProductoKeyPressed
        // TODO add your handling code here:
        AccesoBD bd = new AccesoBD();
        String[] Titulos = {"Código", "Nombre Fabricante"};
        String[] Registro = new String[50];

        String sql = "SELECT * FROM fabricante WHERE id_fabricante LIKE '%" + txtBuscaProducto.getText()+ "%'"
        + "OR nombre_fabricante LIKE '%" + txtBuscaProducto.getText() + "%'";

        model = new DefaultTableModel(null,Titulos);
        try {
            bd.conectaBD();
            Statement sta = bd.getConexion().createStatement();
            ResultSet rs= sta.executeQuery(sql);

            while(rs.next()){
                Registro[0] = rs.getString("id_fabricante");
                Registro[1] = rs.getString("nombre_fabricante");
                model.addRow(Registro);
            }
            jtMuestraFabricantes.setModel(model);
        } catch (Exception ex) {

        }
    }//GEN-LAST:event_txtBuscaProductoKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_MuestraFabricante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_MuestraFabricante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_MuestraFabricante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_MuestraFabricante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_MuestraFabricante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpInventarioFabricantes;
    private javax.swing.JTable jtMuestraFabricantes;
    private javax.swing.JLabel lblTitulo1;
    private javax.swing.JLabel lblTitulo2;
    private javax.swing.JTextField txtBuscaProducto;
    // End of variables declaration//GEN-END:variables
}
