/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectois2;

import java.sql.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Daniela Espinosa
 */
public class Frm_MuestraCliente extends javax.swing.JFrame {

    private DefaultTableModel model;
    public Frm_MuestraCliente() {
        initComponents();
        AjustarVentana();
        try {
            actualizarTabla();
        } catch (Exception ex) {
            
        }
    }
    
    private void AjustarVentana(){
        //Centrar Ventana
        this.setLocationRelativeTo(null);  
        
        //Bloquear Tamanio
        this.setResizable(false);
    }
    
    public final void actualizarTabla() throws Exception{
        DefaultTableModel modelo = new DefaultTableModel();
        AccesoBD bd = new AccesoBD();
        ResultSet rs = bd.getTabla("SELECT cedula, nombres, apellidos, direccion, telefono FROM cliente");
        modelo.setColumnIdentifiers(new Object[]{"Cédula", "Nombres", "Apellidos", "Dirección", "Teléfono"});
        try{
            while(rs.next()){
                modelo.addRow(new Object[]{rs.getString("cedula"), rs.getString("nombres"),
                rs.getString("apellidos"), rs.getString("direccion"), rs.getString("telefono")});
            }
            jtMuestraClientes.setModel(modelo);
        }
        catch(SQLException e){
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpMuestraCliente = new javax.swing.JPanel();
        lblTitulo1 = new javax.swing.JLabel();
        lblTitulo2 = new javax.swing.JLabel();
        txtBuscaCliente = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtMuestraClientes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Listado de Clientes");

        jpMuestraCliente.setBackground(new java.awt.Color(255, 241, 207));

        lblTitulo1.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 36)); // NOI18N
        lblTitulo1.setForeground(new java.awt.Color(38, 63, 68));
        lblTitulo1.setText("Listado de clientes");

        lblTitulo2.setFont(new java.awt.Font("Bauhaus 93", 1, 24)); // NOI18N
        lblTitulo2.setForeground(new java.awt.Color(38, 63, 68));
        lblTitulo2.setText("Búsqueda:");
        lblTitulo2.setPreferredSize(new java.awt.Dimension(34, 40));

        txtBuscaCliente.setPreferredSize(new java.awt.Dimension(6, 45));
        txtBuscaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscaClienteActionPerformed(evt);
            }
        });
        txtBuscaCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscaClienteKeyPressed(evt);
            }
        });

        jtMuestraClientes = new javax.swing.JTable(){
            public boolean isCellEditable (int rowIndex, int colIndex){
                return false;
            }
        };
        jtMuestraClientes.setBackground(new java.awt.Color(255, 241, 207));
        jtMuestraClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtMuestraClientes.setGridColor(new java.awt.Color(38, 63, 68));
        jtMuestraClientes.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jtMuestraClientes);

        javax.swing.GroupLayout jpMuestraClienteLayout = new javax.swing.GroupLayout(jpMuestraCliente);
        jpMuestraCliente.setLayout(jpMuestraClienteLayout);
        jpMuestraClienteLayout.setHorizontalGroup(
            jpMuestraClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMuestraClienteLayout.createSequentialGroup()
                .addGroup(jpMuestraClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpMuestraClienteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jpMuestraClienteLayout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(lblTitulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpMuestraClienteLayout.createSequentialGroup()
                .addGap(0, 127, Short.MAX_VALUE)
                .addComponent(lblTitulo1)
                .addGap(122, 122, 122))
        );
        jpMuestraClienteLayout.setVerticalGroup(
            jpMuestraClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMuestraClienteLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(lblTitulo1)
                .addGap(45, 45, 45)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(jpMuestraClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBuscaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpMuestraCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpMuestraCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscaClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscaClienteActionPerformed

    private void txtBuscaClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscaClienteKeyPressed
        // TODO add your handling code here:
        AccesoBD bd = new AccesoBD();
        String[] Titulos = {"Cédula", "Nombres", "Apellidos", "Direccion", "Teléfono"};
        String[] Registro = new String[50];

        String sql = "SELECT * FROM cliente WHERE cedula LIKE '%" + txtBuscaCliente.getText()+ "%'"
        + "OR nombres LIKE '%" + txtBuscaCliente.getText() + "%'"
        + "OR apellidos LIKE '%" + txtBuscaCliente.getText() + "%'"
        + "OR direccion LIKE '%" + txtBuscaCliente.getText() + "%'"
        + "OR telefono LIKE '%" + txtBuscaCliente.getText() + "%'";

        model = new DefaultTableModel(null,Titulos);
        try {
            bd.conectaBD();
            Statement sta = bd.getConexion().createStatement();
            ResultSet rs= sta.executeQuery(sql);

            while(rs.next()){
                Registro[0] = rs.getString("cedula");
                Registro[1] = rs.getString("nombres");
                Registro[2] = rs.getString("apellidos");
                Registro[3] = rs.getString("direccion");
                Registro[4] = rs.getString("telefono");
                model.addRow(Registro);
            }
            jtMuestraClientes.setModel(model);
        } catch (Exception ex) {

        }
    }//GEN-LAST:event_txtBuscaClienteKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_MuestraCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_MuestraCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_MuestraCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_MuestraCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_MuestraCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpMuestraCliente;
    private javax.swing.JTable jtMuestraClientes;
    private javax.swing.JLabel lblTitulo1;
    private javax.swing.JLabel lblTitulo2;
    private javax.swing.JTextField txtBuscaCliente;
    // End of variables declaration//GEN-END:variables
}
